# Generated by Django 4.0.3 on 2022-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
