# Generated by Django 4.0.3 on 2022-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apictures', '0002_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='image_pic',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
    ]
