# Generated by Django 4.0.3 on 2022-03-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apictures', '0003_remove_image_photo_image_image_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_pic',
        ),
        migrations.AddField(
            model_name='image',
            name='image_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
